# Generated by Django 4.0.3 on 2024-03-17 00:06

from django.db import migrations, models
import django.db.models.deletion
import onlineDB.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('total_area', models.FloatField(blank=True, null=True, verbose_name='Total area (km²)')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Human_wildlife_conflict_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=onlineDB.models.current_year)),
                ('collect_start_date', models.DateField()),
                ('collect_end_date', models.DateField()),
                ('data_level', models.CharField(default='year', max_length=255)),
                ('interaction_without_destruction', models.IntegerField(default=0, null=True)),
                ('interaction_with_destruction', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineDB.block')),
            ],
            options={
                'verbose_name_plural': 'Human wildlife conflict data',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('var_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pillar', models.CharField(choices=[('Human wildlife conflict', 'Human wildlife conflict'), ('Wildlife survey', 'Wildlife survey'), ('Human activity', 'Human activity'), ('Spatial data and landcover', 'Spatial data and landcover')], default=onlineDB.models.current_year, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('sampling_method', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'sampling',
                'ordering': ['sampling_method'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.BooleanField(default='False')),
                ('total_area', models.FloatField(blank=True, null=True, verbose_name='Total area (km²)')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('creation_date', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('scientific_name', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('family', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('errorColor', models.CharField(blank=True, default=' ', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wildlife_dataSmart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=onlineDB.models.current_year)),
                ('level', models.CharField(default='year', max_length=255)),
                ('encounter_rate_min', models.FloatField(blank=True, null=True)),
                ('encounter_rate_max', models.FloatField(blank=True, null=True)),
                ('encounter_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineDB.block')),
                ('site', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineDB.site')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineDB.species')),
            ],
            options={
                'verbose_name_plural': 'Wildlife data smart',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Wildlife_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=onlineDB.models.current_year)),
                ('level', models.CharField(default='block', max_length=255)),
                ('encounter_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineDB.block')),
                ('sampling', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineDB.sampling')),
                ('site', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineDB.site')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineDB.species')),
            ],
            options={
                'verbose_name_plural': 'Wildlife data',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Human_wildlife_conflict_dataSmart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=onlineDB.models.current_year)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data_level', models.CharField(default='year', max_length=255)),
                ('monthly_average_rate_intrusion_with_damage', models.FloatField(blank=True, null=True)),
                ('monthly_average_rate_intrusion_without_damage', models.FloatField(blank=True, null=True)),
                ('monthly_average_rate_intrusion', models.FloatField(blank=True, null=True)),
                ('daily_average_rate_intrusion_with_damage', models.FloatField(blank=True, null=True)),
                ('daily_average_rate_intrusion_without_damage', models.FloatField(blank=True, null=True)),
                ('daily_average_rate_intrusion', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineDB.block')),
                ('id_hwc_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineDB.human_wildlife_conflict_data')),
                ('site', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineDB.site')),
            ],
            options={
                'verbose_name_plural': 'Human wildlife conflict data smart',
                'ordering': ['year'],
            },
        ),
        migrations.AddField(
            model_name='human_wildlife_conflict_data',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineDB.site'),
        ),
        migrations.AddField(
            model_name='block',
            name='site',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineDB.site'),
        ),
    ]
