# Generated by Django 4.0.3 on 2024-03-17 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildlife_data',
            name='level',
        ),
    ]
