# Generated by Django 4.0.3 on 2024-03-13 12:24

from django.db import migrations, models
import django.db.models.deletion
import onlineDB.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human_wildlife_conflict_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=onlineDB.models.current_year)),
                ('collect_start_date', models.DateField()),
                ('collect_end_date', models.DateField()),
                ('interaction_without_destruction', models.IntegerField(blank=True, null=True)),
                ('interaction_with_destruction', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineDB.block')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineDB.site')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Human_wildlife_conflict_dataSmart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=onlineDB.models.current_year)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_average_rate_intrusion_with_damage', models.FloatField(blank=True, null=True)),
                ('monthly_average_rate_intrusion_without_damage', models.FloatField(blank=True, null=True)),
                ('monthly_average_rate_intrusion', models.FloatField(blank=True, null=True)),
                ('daily_average_rate_intrusion_with_damage', models.FloatField(blank=True, null=True)),
                ('daily_average_rate_intrusion_without_damage', models.FloatField(blank=True, null=True)),
                ('daily_average_rate_intrusion', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineDB.block')),
                ('id_hwc_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineDB.human_wildlife_conflict_data')),
                ('site', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineDB.site')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
