# Generated by Django 4.0.3 on 2024-03-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineDB', '0002_human_wildlife_conflict_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human_wildlife_conflict_data',
            options={'ordering': ['year'], 'verbose_name_plural': 'Human wildlife conflict data'},
        ),
        migrations.AlterModelOptions(
            name='human_wildlife_conflict_datasmart',
            options={'ordering': ['year'], 'verbose_name_plural': 'Human wildlife conflict data smart'},
        ),
    ]
