# Generated by Django 4.0.3 on 2024-03-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineDB', '0003_alter_human_wildlife_conflict_data_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('sampling_method', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['sampling_method'],
            },
        ),
    ]
